"""Taint profiles: per-language sources (untrusted input) and sinks (dangerous ops).

A *source* is an operation that introduces untrusted data into the program.
A *sink* is an operation that must never consume untrusted data.

Each sink carries a *category* used to derive a severity and to reason about
the kind of vulnerability (e.g. ``sql`` -> SQL injection, ``command`` -> OS
command injection, ``deserialization`` -> insecure deserialization).
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Dict


@dataclass(frozen=True)
class LanguageProfile:
    name: str
    sources: Dict[str, str]  # dotted call name -> description
    sinks: Dict[str, str]  # dotted call name -> category
    sanitizers: Dict[str, str] = field(default_factory=dict)  # kill taint
    auth_gates: Dict[str, str] = field(default_factory=dict)  # privilege boundaries


# Severity ordering per sink category (used to rank findings).
CATEGORY_SEVERITY: Dict[str, str] = {
    "command_execution": "critical",
    "code_execution": "critical",
    "deserialization": "critical",
    "sql": "high",
    "path_traversal": "high",
    "buffer_overflow": "high",
    "format_string": "high",
    "file_inclusion": "critical",
    "memory_unsafe": "high",
    "template_injection": "high",
    "file_write": "medium",
    "logging": "medium",
    "network": "medium",
}

PYTHON = LanguageProfile(
    name="python",
    sources={
        # builtins / stdlib
        "input": "interactive standard input",
        "raw_input": "interactive standard input (py2)",
        "sys.stdin.read": "standard input stream",
        "sys.stdin.readline": "standard input stream",
        "sys.argv": "command-line arguments",
        "os.environ.get": "environment variable",
        "os.environ.getenv": "environment variable",
        "socket.recv": "network socket data",
        "socket.recvfrom": "network socket data",
        "urllib.request.urlopen": "remote HTTP response",
        "urllib.request.urlopen.read": "remote HTTP response body",
        "requests.get": "remote HTTP response",
        "requests.post": "remote HTTP response",
        # web frameworks
        "request.args.get": "HTTP query parameter",
        "request.form.get": "HTTP form field",
        "request.json.get": "HTTP JSON body",
        "request.files.get": "HTTP uploaded file",
        "flask.request.args.get": "HTTP query parameter",
        "django.http.HttpRequest.GET.get": "HTTP query parameter",
        # web frameworks -- attribute-style sources (framework summaries)
        "request.args": "Flask query parameters (attribute source)",
        "request.form": "Flask form fields (attribute source)",
        "request.values": "Flask combined parameters (attribute source)",
        "request.json": "Flask JSON body (attribute source)",
        "request.data": "Flask raw body (attribute source)",
        "request.GET": "Django query parameters (attribute source)",
        "request.POST": "Django POST data (attribute source)",
        "request.FILES": "Django uploaded files (attribute source)",
        "request.COOKIES": "Django cookies (attribute source)",
        "request.body": "Django raw body (attribute source)",
        "request.META": "Django request metadata (attribute source)",
        "self.request.GET": "Django query parameters (attribute source)",
        "self.request.POST": "Django POST data (attribute source)",
        # web frameworks -- .get()/method-style accessor variants
        "request.GET.get": "HTTP query parameter",
        "request.POST.get": "HTTP form field",
        "request.COOKIES.get": "HTTP cookie",
        "request.FILES.get": "HTTP uploaded file",
        "request.values.get": "HTTP combined parameter",
        "request.META.get": "HTTP request metadata",
        "self.request.GET.get": "HTTP query parameter",
        "self.request.POST.get": "HTTP form field",
        # filesystem
        "open": "file contents (untrusted path)",
        "pathlib.Path.read_text": "file contents",
        "pathlib.Path.read_bytes": "file contents",
        "file.read": "file contents",
        "pickle.load": "serialized object",
        "pickle.loads": "serialized object",
        "yaml.load": "YAML document",
        "json.load": "JSON document",
        "json.loads": "JSON document",
    },
    sinks={
        "eval": "code_execution",
        "exec": "code_execution",
        "compile": "code_execution",
        "__import__": "code_execution",
        "importlib.import_module": "code_execution",
        "os.system": "command_execution",
        "os.popen": "command_execution",
        "subprocess.call": "command_execution",
        "subprocess.run": "command_execution",
        "subprocess.Popen": "command_execution",
        "subprocess.check_call": "command_execution",
        "subprocess.check_output": "command_execution",
        "subprocess.getoutput": "command_execution",
        "commands.getoutput": "command_execution",
        "pickle.load": "deserialization",
        "pickle.loads": "deserialization",
        "yaml.load": "deserialization",
        "yaml.unsafe_load": "deserialization",
        "sqlite3.connect.execute": "sql",
        "sqlite3.Connection.execute": "sql",
        "cursor.execute": "sql",
        "connection.execute": "sql",
        "db.execute": "sql",
        # ORM / raw-SQL framework summaries
        "RawSQL": "sql",
        "raw": "sql",
        "extra": "sql",
        "text": "sql",
        "executescript": "sql",
        "cursor.executemany": "sql",
        # template injection (SSTI) framework summaries
        "render_template_string": "code_execution",
        "from_string": "code_execution",
        "open": "file_write",
        "pathlib.Path.open": "file_write",
        "os.remove": "path_traversal",
        "os.unlink": "path_traversal",
        "os.rmdir": "path_traversal",
        "logging.debug": "logging",
        "logging.info": "logging",
        "logging.warning": "logging",
        "logging.error": "logging",
    },
    sanitizers={
        # Casting / validation
        "int": "numeric cast",
        "float": "numeric cast",
        "str": "string cast",
        "bool": "boolean cast",
        # HTML / markup escaping
        "html.escape": "HTML escaping",
        "markupsafe.escape": "HTML escaping",
        "cgi.escape": "HTML escaping",
        "bleach.clean": "HTML sanitization",
        "django.utils.html.escape": "HTML escaping",
        # SQL / shell / regex escaping
        "re.escape": "regex escaping",
        "shlex.quote": "shell quoting",
        "pymysql.escape_string": "SQL escaping",
        # Cryptographic / validation helpers
        "hmac.compare_digest": "constant-time comparison",
        "uuid.UUID": "UUID validation",
    },
    auth_gates={
        # Decorators / functions that mark a privilege boundary.
        "login_required": "authentication gate",
        "permission_required": "authorization gate",
        "require_auth": "authentication gate",
        "auth_required": "authentication gate",
        "authenticate": "authentication gate",
        "check_auth": "authentication gate",
        "is_authenticated": "authentication check",
        "has_permission": "authorization check",
        "require_user": "authentication gate",
        "require_role": "authorization gate",
        "verify_token": "token verification",
        "token_required": "token gate",
        "admin_required": "authorization gate",
        "staff_member_required": "authorization gate",
    },
)

JAVASCRIPT = LanguageProfile(
    name="javascript",
    sources={
        "process.argv": "command-line arguments",
        "process.env": "environment variables",
        "req.body": "HTTP request body",
        "req.query": "HTTP query string",
        "req.params": "HTTP route parameters",
        "document.location": "browser location",
        "document.getElementById": "DOM element",
        "window.location.hash": "URL fragment",
        "localStorage.getItem": "local storage",
        "readFileSync": "file contents",
        "fs.readFileSync": "file contents",
    },
    sinks={
        "eval": "code_execution",
        "Function": "code_execution",
        "exec": "code_execution",
        "child_process.exec": "command_execution",
        "child_process.execSync": "command_execution",
        "child_process.spawn": "command_execution",
        "child_process.fork": "code_execution",
        "document.write": "code_execution",
        "innerHTML": "code_execution",
        "outerHTML": "code_execution",
        "insertAdjacentHTML": "code_execution",
        "JSON.parse": "deserialization",
        "sqlite3.run": "sql",
        "db.query": "sql",
        "db.execute": "sql",
        "connection.query": "sql",
        "fs.writeFileSync": "file_write",
        "fs.writeFile": "file_write",
        "fs.rmSync": "path_traversal",
    },
    sanitizers={
        "escapeHtml": "HTML escaping",
        "encodeURIComponent": "URI encoding",
        "sanitizeHtml": "HTML sanitization",
        "mongo-sanitize": "NoSQL sanitization",
        "validator.escape": "string escaping",
        "Number": "numeric cast",
        "parseInt": "numeric cast",
    },
)

C = LanguageProfile(
    name="c",
    sources={
        "argv": "command-line arguments",
        "getenv": "environment variable",
        "fgets": "file/stdio input",
        "gets": "unsafe stdio input",
        "scanf": "formatted stdio input",
        "read": "raw file descriptor read",
        "recv": "network socket data",
        "recvfrom": "network socket data",
        "getline": "line input",
        "fread": "file read",
    },
    sinks={
        "system": "command_execution",
        "popen": "command_execution",
        "execl": "command_execution",
        "execlp": "command_execution",
        "execle": "command_execution",
        "execv": "command_execution",
        "execvp": "command_execution",
        "sprintf": "format_string",
        "vsprintf": "format_string",
        "strcpy": "buffer_overflow",
        "strcat": "buffer_overflow",
        "memcpy": "buffer_overflow",
        "strncpy": "buffer_overflow",
        "gets": "buffer_overflow",
        "printf": "format_string",
        "fprintf": "format_string",
        "snprintf": "format_string",
    },
    sanitizers={"snprintf": "bounded format"},
)

CPP = LanguageProfile(
    name="cpp",
    sources={
        "argv": "command-line arguments",
        "getenv": "environment variable",
        "std::getline": "line input",
        "std::cin": "standard input",
        "fgets": "stdio input",
        "read": "raw read",
        "recv": "network socket data",
        "std::ifstream.read": "file read",
    },
    sinks={
        "system": "command_execution",
        "popen": "command_execution",
        "execl": "command_execution",
        "execv": "command_execution",
        "std::system": "command_execution",
        "sprintf": "format_string",
        "strcpy": "buffer_overflow",
        "strcat": "buffer_overflow",
        "memcpy": "buffer_overflow",
        "std::string::c_str": "format_string",
    },
)

RUST = LanguageProfile(
    name="rust",
    sources={
        "std::env::args": "command-line arguments",
        "std::env::var": "environment variable",
        "std::io::stdin": "standard input",
        "read_line": "line input",
        "read_to_string": "file/string input",
        "std::fs::read_to_string": "file contents",
        "TcpStream::read": "network socket data",
        "recv": "network socket data",
    },
    sinks={
        "std::process::Command": "command_execution",
        "Command::new": "command_execution",
        "std::process::Command::new": "command_execution",
        "std::fs::remove_file": "path_traversal",
        "std::fs::write": "file_write",
        "std::fs::File::create": "file_write",
        "eval": "code_execution",
        "unsafe": "memory_unsafe",
    },
)

CSHARP = LanguageProfile(
    name="csharp",
    sources={
        "Console.ReadLine": "standard input",
        "args": "command-line arguments",
        "Environment.GetEnvironmentVariable": "environment variable",
        "Request.QueryString": "HTTP query string",
        "Request.Form": "HTTP form field",
        "HttpContext.Request": "HTTP request",
        "WebRequest": "remote HTTP response",
        "File.ReadAllText": "file contents",
        "StreamReader.ReadToEnd": "file/stream contents",
    },
    sinks={
        "Process.Start": "command_execution",
        "System.Diagnostics.Process.Start": "command_execution",
        "DllImport": "code_execution",
        "Marshal.Copy": "buffer_overflow",
        "File.WriteAllText": "file_write",
        "File.Delete": "path_traversal",
        "Directory.Delete": "path_traversal",
        "SqlCommand": "sql",
        "ExecuteScalar": "sql",
        "ExecuteReader": "sql",
        "XmlSerializer.Deserialize": "deserialization",
        "BinaryFormatter.Deserialize": "deserialization",
        "JavaScriptSerializer.Deserialize": "deserialization",
    },
)

GO = LanguageProfile(
    name="go",
    sources={
        "os.Args": "command-line arguments",
        "os.Getenv": "environment variable",
        "r.URL.Query": "HTTP query string",
        "r.FormValue": "HTTP form field",
        "r.URL.Path": "HTTP route parameter",
        "http.Request": "HTTP request",
        "os.Stdin": "standard input",
        "bufio.NewReader": "buffered input",
        "io.ReadAll": "stream contents",
        "os.ReadFile": "file contents",
    },
    sinks={
        "os/exec.Command": "command_execution",
        "exec.Command": "command_execution",
        "os/exec.CommandContext": "command_execution",
        "db.Query": "sql",
        "db.Exec": "sql",
        "database/sql.Query": "sql",
        "os.Remove": "path_traversal",
        "os.RemoveAll": "path_traversal",
        "os.WriteFile": "file_write",
        "template.HTML": "code_execution",
        "template.JS": "code_execution",
        "json.Unmarshal": "deserialization",
        "gob.NewDecoder": "deserialization",
    },
)

PHP = LanguageProfile(
    name="php",
    sources={
        "$_GET": "HTTP query parameter",
        "$_POST": "HTTP form field",
        "$_REQUEST": "HTTP request parameter",
        "$_COOKIE": "HTTP cookie",
        "$_FILES": "HTTP uploaded file",
        "file_get_contents": "file/remote contents",
        "fgets": "file/stdio input",
        "php://input": "HTTP raw body",
        "getenv": "environment variable",
        "$_SERVER": "server/environment metadata",
    },
    sinks={
        "eval": "code_execution",
        "assert": "code_execution",
        "system": "command_execution",
        "exec": "command_execution",
        "shell_exec": "command_execution",
        "passthru": "command_execution",
        "proc_open": "command_execution",
        "popen": "command_execution",
        "include": "file_inclusion",
        "require": "file_inclusion",
        "include_once": "file_inclusion",
        "require_once": "file_inclusion",
        "unserialize": "deserialization",
        "mysqli_query": "sql",
        "mysql_query": "sql",
        "query": "sql",
        "unlink": "path_traversal",
        "move_uploaded_file": "file_write",
    },
    sanitizers={
        "htmlspecialchars": "HTML escaping",
        "htmlentities": "HTML escaping",
        "addslashes": "string escaping",
        "mysqli_real_escape_string": "SQL escaping",
        "escapeshellarg": "shell quoting",
        "intval": "numeric cast",
    },
)

RUBY = LanguageProfile(
    name="ruby",
    sources={
        "gets": "standard input",
        "ARGV": "command-line arguments",
        "ENV": "environment variable",
        "params": "HTTP request parameter",
        "request.params": "HTTP request parameter",
        "request.query_parameters": "HTTP query string",
        "File.read": "file contents",
        "IO.read": "file/stream contents",
        "cookies": "HTTP cookie",
        "params[:": "HTTP parameter (symbol access)",
    },
    sinks={
        "eval": "code_execution",
        "system": "command_execution",
        "exec": "command_execution",
        "`": "command_execution",
        "spawn": "command_execution",
        "IO.popen": "command_execution",
        "Open3.capture3": "command_execution",
        "Marshal.load": "deserialization",
        "YAML.load": "deserialization",
        "YAML.unsafe_load": "deserialization",
        "File.delete": "path_traversal",
        "FileUtils.rm_rf": "path_traversal",
        "execute": "sql",
        "render": "template_injection",
        "render_to_string": "template_injection",
    },
    sanitizers={
        "CGI.escape": "HTML escaping",
        "ERB::Util.html_escape": "HTML escaping",
        "Shellwords.escape": "shell quoting",
        "to_i": "numeric cast",
    },
)

PROFILES: Dict[str, LanguageProfile] = {
    "python": PYTHON,
    "javascript": JAVASCRIPT,
    "c": C,
    "cpp": CPP,
    "rust": RUST,
    "csharp": CSHARP,
    "go": GO,
    "php": PHP,
    "ruby": RUBY,
}
