#!/usr/bin/env python3
"""Regenerate the paper figures/tables from the benchmark results.

Reads `benchmarks/oracle_results.json` and writes `docs/{en,es}/figs/oracle.tex`
(the cost curve + per-signal AUC table). Run after `benchmarks/run_oracle.py`.
"""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
RESULTS = ROOT / "benchmarks" / "oracle_results.json"

_LABELS = {
    "en": {"x": "\\# verification queries (sink candidates)", "y": "cumulative recall",
           "title": "Cost curve: cumulative recall vs.\\ verification budget",
           "signal": "Signal", "auc": "AUC [95\\% CI]"},
    "es": {"x": "\\# consultas de verificación (candidatos)", "y": "recall acumulado",
           "title": "Curva de costo: recall acumulado vs.\\ presupuesto de verificación",
           "signal": "Señal", "auc": "AUC [IC 95\\%]"},
}

_ORDER = ["dfs", "taint", "field", "random"]


def figure_tex(data: dict, lang: str) -> str:
    lb = _LABELS[lang]
    curves = data["curves"]
    budget = max(len(v) for v in curves.values())
    ax = []
    styles = {"dfs": "dashed", "taint": "solid", "field": "densely dotted", "random": "dashdotted"}
    for name in _ORDER:
        pts = " ".join(f"({i + 1},{v:.3f})" for i, v in enumerate(curves[name]))
        ax.append(
            f"\\addplot+[mark=*, {styles[name]}, thick] coordinates {{{pts}}};\n"
            f"\\addlegendentry{{{name}}}"
        )
    aucs = data.get("signals_auc", {})
    rows = " \\\\\n".join(
        f"{k} & {v['auc']:.3f} [{v['ci95'][0]:.3f}, {v['ci95'][1]:.3f}]"
        for k, v in aucs.items()
    )
    return f"""% AUTO-GENERATED by scripts/make_figures.py -- do not edit by hand.
\\begin{{figure}}[h]
\\centering
\\begin{{tikzpicture}}
\\begin{{axis}}[
  width=0.92\\linewidth, height=5.2cm,
  xlabel={{{lb['x']}}}, ylabel={{{lb['y']}}},
  xmin=1, xmax={budget}, ymin=0.4, ymax=1.03,
  legend pos=south east, grid=both, grid style=dotted,
  title={{{lb['title']}}},
]
{chr(10).join(ax)}
\\end{{axis}}
\\end{{tikzpicture}}
\\end{{figure}}

\\begin{{center}}
\\small
\\begin{{tabular}}{{lc}}
\\toprule
{lb['signal']} & {lb['auc']} \\\\
\\midrule
{rows} \\\\
\\bottomrule
\\end{{tabular}}
\\end{{center}}
"""


def main() -> int:
    data = json.loads(RESULTS.read_text())
    for lang in ("en", "es"):
        out = ROOT / "docs" / lang / "figs" / "oracle.tex"
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(figure_tex(data, lang))
        print(f"wrote {out.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
